### ISSUE TITLE
DJI Pilot2 实际接口调用与源代码有出入

### ISSUE THREAD

**Issue by VVFtang** [dji-sdk/DJI-Cloud-API-Demo#1]
目前发现有以下接口存在出入
request uri->/media/api/v1/workspaces/e3dea0f5-37f2-4d79-ae58-490af3228069/files/tiny-fingerprints
Request method 'POST' not supported

request uri->/storage/api/v1/workspaces/e3dea0f5-37f2-4d79-ae58-490af3228069/sts
Request method 'GET' not supported

request uri->/manage/api/v1/token/refresh
Request method 'GET' not supported

**Comment by DJIsean** [comment]
> 目前发现有以下接口存在出入 request uri->/media/api/v1/workspaces/e3dea0f5-37f2-4d79-ae58-490af3228069/files/tiny-fingerprints Request method 'POST' not supported
> 
> request uri->/storage/api/v1/workspaces/e3dea0f5-37f2-4d79-ae58-490af3228069/sts Request method 'GET' not supported
> 
> request uri->/manage/api/v1/token/refresh Request method 'GET' not supported

tiny-fingerprints 接口是Pilot版本中存在变动。其他两个接口已经修改postman中数据。
