### ISSUE TITLE
M3T not working

### ISSUE THREAD

**Issue by skymic** [dji-sdk/DJI-Cloud-API-Demo#10]
"device not connect". Able to log in and see the test group one but the device will not connect on the latest docker instance with the latest firmware update that was just released. M30T connects without error.  Appears to be a problem with the websocket possibly.

**Comment by DJIsean** [comment]
The latest version of Pilot2 does not support http, you have to use https. Maybe you can rollback the remote control version. Pilot2 will reopen http in the next version.

**Comment by lovesmall** [comment]
> The latest version of Pilot2 does not support http, you have to use https. Maybe you can rollback the remote control version. Pilot2 will reopen http in the next version.

Hi, I'm working on my local dev environment (HTTP only). My M3T Pilot2 is version 02.00.0303, still showing "Devise not found" after I logged in successfully. Any plan when will the new Pilot2 released?

**Comment by geospace12** [comment]
Pilot 2 was suppose to be fixed. BUT ITS NOT!!!!!  6.0.1.6
