### ISSUE TITLE
HTTP

### ISSUE THREAD

**Issue by dronematt** [dji-sdk/DJI-Cloud-API-Demo#13]
Pinpoints and Map Features are not working with DJI Pilot 2 App Android: V5.1.1.8

**Comment by DJIsean** [comment]
#10 Maybe your problem is the same.

**Comment by lovesmall** [comment]
Hi @DJIsean, Any plan when the new Pilot2 (that supports HTTP) will release?

**Comment by geospace12** [comment]
Pilot 2 was suppose to be fixed. BUT ITS NOT!!!!!  6.0.1.6

**Comment by emilianocds** [comment]
Is the screenshot attached the same issue?

![cloud api ws disconnect](https://user-images.githubusercontent.com/55559063/223202957-195061e5-115b-4d5a-845c-6737491149e2.png)

**Comment by DJIsean** [comment]
HTTP is already supported in Pilot2 version V6.1 or higher. [https://www.dji.com/matrice-30/downloads](https://www.dji.com/matrice-30/downloads)
