### ISSUE TITLE
对OSS模块中一些想法

### ISSUE THREAD

**Issue by VVFtang** [dji-sdk/DJI-Cloud-API-Demo#2]
1. 每次createClient是否有必要，不妨注入到容器中？
2. 使用getObject方法来判断文件是否存在是否过于暴力？用doesObjectExist应该更合适。

**Comment by DJIsean** [comment]
👍

**Comment by DJIsean** [comment]
https://github.com/dji-sdk/DJI-Cloud-API-Demo/commit/2d8ded3e77b22e44985265ca4063102662e452c1
