### ISSUE TITLE
文件不上传: 循环调 fast-upload  不上传

### ISSUE THREAD

**Issue by RedForc** [dji-sdk/DJI-Cloud-API-Demo#21]
无人机的相册里就一个文件要上传OSS
不停的调 API request uri: /media/api/v1/workspaces/e3dea0f5-37f2-4d79-ae58-490af3228069/fast-upload
后台 查数据库 无文件 返回:
ResponseResult.error(file.getFingerprint() + "don't exist.");
然后一直掉接口 fast-upload 不获取STS上传文件

前后端都是 main分支

**Comment by RedForc** [comment]
STS 配的可能有问题

**Comment by dsw0917** [comment]
问题解决了吗？
