### ISSUE TITLE
循环依赖

### ISSUE THREAD

**Issue by pigeon2049** [dji-sdk/DJI-Cloud-API-Demo#36]
Description:

The dependencies of some of the beans in the application context form a cycle:

   drcController (field private com.dji.sample.control.service.IDrcService com.dji.sample.control.controller.DrcController.drcService)
┌─────┐
|  drcServiceImpl defined in file 
[\target\classes\com\dji\sample\control\service\impl\DrcServiceImpl.class]
↑     ↓
|  waylineJobServiceImpl (field private com.dji.sample.control.service.IDrcService com.dji.sample.wayline.service.impl.WaylineJobServiceImpl.drcService)
└─────┘

Action:

Relying upon circular references is discouraged and they are prohibited by default. Update your application to remove the dependency cycle between beans. As a last resort, it may be possible to break the cycle automatically by setting spring.main.allow-circular-references to true.

**Comment by DJIsean** [comment]
https://github.com/dji-sdk/DJI-Cloud-API-Demo/commit/d68e3d3eaea8b387de9760472e6ff730633bf805
