### ISSUE TITLE
After setup get Errors/Warnings Agora-SDK and User Admin / Update

### ISSUE THREAD

**Issue by maka1000** [dji-sdk/DJI-Cloud-API-Demo#4]
We setup DJI-Cloud-API-Demo but get warnings/errors from Agora-SDK in console: I don't understand what the warning means (See screenshot below). What do the yellow "Agora-SDK" warning means? I see the red "Agora-SDK" Error means that we should use a https connection, right?

Is it possible to manage users in dji-cloud-api demo?

When an update will published: How can I update it?
![image](https://user-images.githubusercontent.com/19875641/190352121-d9795483-c32e-4f03-acef-d0c3a24af394.png)

**Comment by DJIsean** [comment]
"Agora-SDK" Error means that we should use a https connection, right? That's right. You have to use https protocol. But you can use localhost for development.

If you want to manage users, you can develop by yourself. There is no such function in the demo. If you want to manage users, you can develop it yourself.

I will update the demo version with the Cloud API version.

**Comment by DJIsean** [comment]
> Hi, we have the same problem. since we want to use a local server, we cannot create a certificate. and this network is not connected to the internet. so how can we set up and use an "offline" server. we cannot use localhost on the remote control. I hope you can help me in the short term. Best wishes orichienal

This is a limitation of Agora. Agora cannot be used if you are only using Cloud API on a local server.

**Comment by orichienal** [comment]
but is there a solution to do it on a local server?

**Comment by DJIsean** [comment]
> but is there a solution to do it on a local server?

maybe you can use the rtmp protocol for live streaming.
