### ISSUE TITLE
1.9.0 - is there any documentation how one could make use of the new WebRTC Whip implementation?

### ISSUE THREAD

**Issue by neilyoung** [dji-sdk/DJI-Cloud-API-Demo#53]
... as subject says

**Comment by neilyoung** [comment]
Disregard please. This should be obvious

**Comment by neilyoung** [comment]
Ehem... No. It seems to be obvious from the configuration in the backend, but it looks like it would also need updates in RC and Dock (?).... Because - it doesn't work...

**Comment by xarauzo** [comment]
How did you make it work @neilyoung ?
