### ISSUE TITLE
Wrong emqx image used

### ISSUE THREAD

**Issue by RobertoD91** [dji-sdk/DJI-Cloud-API-Demo#6]
This issue is about the docker version.
Please switch from `emqx` to `emqx/emqx:4.4.9` image
The `emqx` has some bug.
https://github.com/emqx/emqx/issues/9043

**Comment by DJIsean** [comment]
Thanks, we will update the version in the next docker package.

**Comment by DJIsean** [comment]
The latest docker package already uses official image `emqx:4.4`.
