### ISSUE TITLE
请问Cloud: Disconnect 是什么原因

### ISSUE THREAD

**Issue by 673181695** [dji-sdk/DJI-Cloud-API-Demo#63]
版本 pilot2 9.0.5.31
部署docker版demo
硬件：3E

如图：
<img width="570" alt="image" src="https://github.com/dji-sdk/DJI-Cloud-API-Demo/assets/4152256/e1445d77-a487-49cc-b523-da3a24c632d3">

**Comment by 673181695** [comment]
已解决：
1.mqtt配置要改，我现在改成直接连接mqtt，后面再看是否能通过NGINX转发
2.update_backend.sh脚本有点错误，把其中"name=cloud_api_sample_1" 改成 "name=cloud_api_sample-1"，下划线改成横线

**Comment by YangZhenFu** [comment]
> 已解决： 1.mqtt配置要改，我现在改成直接连接mqtt，后面再看是否能通过NGINX转发 2.update_backend.sh脚本有点错误，把其中"name=cloud_api_sample_1"改成"name=cloud_api_sample-1"，下划线改成横线
你好，我也遇到了同样的问题，麻烦把解放方式截图看一下吧

**Comment by 673181695** [comment]
你好，我才看到邮件，你解决了吗




黎彬
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dji-sdk/DJI-Cloud-API-Demo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月16日(星期二) 上午10:20
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [dji-sdk/DJI-Cloud-API-Demo] 请问Cloud: Disconnect 是什么原因 (Issue #63)





  
已解决： 1.mqtt配置要改，我现在改成直接连接mqtt，后面再看是否能通过NGINX转发 2.update_backend.sh脚本有点错误，把其中"name=cloud_api_sample_1"改成"name=cloud_api_sample-1"，下划线改成横线
 你好，我也遇到了同样的问题，麻烦把解放方式截图看一下吧

**Comment by xwh1108** [comment]
> 你好，我才看到邮件，你解决了吗 黎彬 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "dji-sdk/DJI-Cloud-API-Demo" ***@***.***&gt;; 发送时间:&nbsp;2024年7月16日(星期二) 上午10:20 ***@***.***&gt;; ***@***.***&gt;;"State ***@***.***&gt;; 主题:&nbsp;Re: [dji-sdk/DJI-Cloud-API-Demo] 请问Cloud: Disconnect 是什么原因 (Issue #63) 已解决： 1.mqtt配置要改，我现在改成直接连接mqtt，后面再看是否能通过NGINX转发 2.update_backend.sh脚本有点错误，把其中"name=cloud_api_sample_1"改成"name=cloud_api_sample-1"，下划线改成横线 你好，我也遇到了同样的问题，麻烦把解放方式截图看一下吧 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

mqtt配置怎么改?我后端链接上了 pilot链接不上 看网络返回到mqtt地址也是正确的

**Comment by zy-zxy-mm** [comment]
你好，我是直接连接的，但是还是出现了这个问题
