### ISSUE TITLE
com.dji.sdk.exception.CloudSDKVersionException: The current CloudSDK version(1.0.3) does not support this thing version(1.3.1), please replace the corresponding CloudSDK version.)

### ISSUE THREAD

**Issue by Loloncio** [dji-sdk/DJI-Cloud-API-Demo#85]
I am trying to start using Cloud API, I have managed to start the frontend and backend but when i try to connect the dock2 and matrice 3TD i get this error in the backend: "The current CloudSDK version(1.0.3) does not support this thing version(1.3.1), please replace the corresponding CloudSDK version.)". 
I downloaded the Cloud API yesterday so it is at the latest version, I also updated today the dron, the dock and the remote but it still does not work.
Dock2 and M3TD version: 10.01.3205
Pilot2 version: 10.1.5.10
Yesterday I managed to see the drone in the cloud api but it said disconected right off.
Also the dock and cloud API does connect to mqtt

**Comment by Loloncio** [comment]
ok, it was a configuration problem in the enumerations

**Comment by YaOdna-zxx** [comment]
@Loloncio    I encountered the same problem as you and I tried to modify it，, but it was still the same mistake

![Image](https://github.com/user-attachments/assets/2cea93e7-8e3f-48ef-a1d1-a6b60480c725)
